In [66]:
import numpy as np

#### A. REPRODUCIBLE NORMALIZATION PROBLEM

In [67]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))
X

array([[48, 11, 15, 67, 21],
       [11, 41, 13, 66, 24],
       [71, 79, 53, 67, 70],
       [77, 35, 91, 19, 96],
       [35, 54, 37, 41, 17]], dtype=int32)

In [68]:
x = np.mean(X)
x

np.float64(46.36)

In [69]:
a = np.std(X)
a

np.float64(25.864075471588002)

In [70]:
X_normalized = (X-x)/a
X_normalized

array([[ 0.06340841, -1.36714726, -1.2124926 ,  0.79801809, -0.98051059],
       [-1.36714726, -0.20723725, -1.28981993,  0.75935442, -0.86451959],
       [ 0.95267275,  1.26198209,  0.25672675,  0.79801809,  0.91400909],
       [ 1.18465476, -0.43921926,  1.72594609, -1.05783793,  1.91926443],
       [-0.43921926,  0.29539042, -0.36189192, -0.20723725, -1.13516526]])

In [71]:
X

array([[48, 11, 15, 67, 21],
       [11, 41, 13, 66, 24],
       [71, 79, 53, 67, 70],
       [77, 35, 91, 19, 96],
       [35, 54, 37, 41, 17]], dtype=int32)

In [72]:
X_normalized

array([[ 0.06340841, -1.36714726, -1.2124926 ,  0.79801809, -0.98051059],
       [-1.36714726, -0.20723725, -1.28981993,  0.75935442, -0.86451959],
       [ 0.95267275,  1.26198209,  0.25672675,  0.79801809,  0.91400909],
       [ 1.18465476, -0.43921926,  1.72594609, -1.05783793,  1.91926443],
       [-0.43921926,  0.29539042, -0.36189192, -0.20723725, -1.13516526]])

In [73]:
print("Mean:", round(X_normalized.mean()))

Mean: 0


In [74]:
print("Standard Deviation:", round(X_normalized.std()))

Standard Deviation: 1


In [75]:
np.save("X_normalized", X_normalized)

#### B. CUBES DIVISIBLE BY 4 PROBLEM

In [76]:
C = (np.linspace(1,100,100) ** 3).reshape(10,10)
C

array([[1.00000e+00, 8.00000e+00, 2.70000e+01, 6.40000e+01, 1.25000e+02,
        2.16000e+02, 3.43000e+02, 5.12000e+02, 7.29000e+02, 1.00000e+03],
       [1.33100e+03, 1.72800e+03, 2.19700e+03, 2.74400e+03, 3.37500e+03,
        4.09600e+03, 4.91300e+03, 5.83200e+03, 6.85900e+03, 8.00000e+03],
       [9.26100e+03, 1.06480e+04, 1.21670e+04, 1.38240e+04, 1.56250e+04,
        1.75760e+04, 1.96830e+04, 2.19520e+04, 2.43890e+04, 2.70000e+04],
       [2.97910e+04, 3.27680e+04, 3.59370e+04, 3.93040e+04, 4.28750e+04,
        4.66560e+04, 5.06530e+04, 5.48720e+04, 5.93190e+04, 6.40000e+04],
       [6.89210e+04, 7.40880e+04, 7.95070e+04, 8.51840e+04, 9.11250e+04,
        9.73360e+04, 1.03823e+05, 1.10592e+05, 1.17649e+05, 1.25000e+05],
       [1.32651e+05, 1.40608e+05, 1.48877e+05, 1.57464e+05, 1.66375e+05,
        1.75616e+05, 1.85193e+05, 1.95112e+05, 2.05379e+05, 2.16000e+05],
       [2.26981e+05, 2.38328e+05, 2.50047e+05, 2.62144e+05, 2.74625e+05,
        2.87496e+05, 3.00763e+05, 3.14432e+05

In [77]:
C.shape

(10, 10)

In [78]:
div_by_4 = C[C % 4 == 0]
div_by_4

array([8.00000e+00, 6.40000e+01, 2.16000e+02, 5.12000e+02, 1.00000e+03,
       1.72800e+03, 2.74400e+03, 4.09600e+03, 5.83200e+03, 8.00000e+03,
       1.06480e+04, 1.38240e+04, 1.75760e+04, 2.19520e+04, 2.70000e+04,
       3.27680e+04, 3.93040e+04, 4.66560e+04, 5.48720e+04, 6.40000e+04,
       7.40880e+04, 8.51840e+04, 9.73360e+04, 1.10592e+05, 1.25000e+05,
       1.40608e+05, 1.57464e+05, 1.75616e+05, 1.95112e+05, 2.16000e+05,
       2.38328e+05, 2.62144e+05, 2.87496e+05, 3.14432e+05, 3.43000e+05,
       3.73248e+05, 4.05224e+05, 4.38976e+05, 4.74552e+05, 5.12000e+05,
       5.51368e+05, 5.92704e+05, 6.36056e+05, 6.81472e+05, 7.29000e+05,
       7.78688e+05, 8.30584e+05, 8.84736e+05, 9.41192e+05, 1.00000e+06])

In [83]:
div_by_4.shape

(50,)

In [79]:
np.save("div_by_4", div_by_4)

#### C. ABOVE-MEAN SQUARES PROBLEM

In [80]:
S = (np.linspace(1,36,36) ** 2).reshape(6,6)
S

array([[1.000e+00, 4.000e+00, 9.000e+00, 1.600e+01, 2.500e+01, 3.600e+01],
       [4.900e+01, 6.400e+01, 8.100e+01, 1.000e+02, 1.210e+02, 1.440e+02],
       [1.690e+02, 1.960e+02, 2.250e+02, 2.560e+02, 2.890e+02, 3.240e+02],
       [3.610e+02, 4.000e+02, 4.410e+02, 4.840e+02, 5.290e+02, 5.760e+02],
       [6.250e+02, 6.760e+02, 7.290e+02, 7.840e+02, 8.410e+02, 9.000e+02],
       [9.610e+02, 1.024e+03, 1.089e+03, 1.156e+03, 1.225e+03, 1.296e+03]])

In [81]:
S_mean = np.mean(S)
S_mean

np.float64(450.1666666666667)

In [82]:
above_mean = S[S > S_mean]
above_mean

array([ 484.,  529.,  576.,  625.,  676.,  729.,  784.,  841.,  900.,
        961., 1024., 1089., 1156., 1225., 1296.])

In [84]:
above_mean.shape

(15,)

In [85]:
np.save("above_mean", above_mean)